main:
  - name: Inicio
    url: ""
    weight: 1
  - name: Sobre mi
    url: "#service"
    weight: 2
  - name: ¿Piso Pélvico?
    url: "#resume"
    weight: 3
  - name: Servicios
    url: "#about"
    weight: 4
  - name: Core Restore
    url: "#product"
    weight: 5
  - name: Testimonios
    url: "#testimonial"
    weight: 6
  - name: Blog
    url: "#blog"
    weight: 7
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Agenda tu cita
    url: "contact"
    weight: 2
  - name: Products
    url: "product"
    weight: 3
  - name: Blog
    url: "blog"
    weight: 4
