# In the Name of God, the Originator the Creative

titleSeparator: "-"
titleAddition: Fisioterapia Pélvica Experta | Cristal Sarabia, Fisioterapeuta Especializada
description: >-
  Recupera tu bienestar con la fisioterapia pélvica de Cristal Sarabia.
  Experta en tratamientos para el suelo pélvico, ofreciendo soluciones personalizadas.
  Confía en nuestra experiencia para mejorar tu calidad de vida.
# Open Graph and Twitter Cards
images:
  - favicon.ico
ogLocale: en_US
# Used in Open Graph
titleHome: Cristal Sarabia
twitterSite: "@cristalsarabia"
twitterCreator: "@henkverlinde"
# It may be Person
schemaType: Organization
schemaName: Hyas
schemaAuthor: Henk Verlinde
schemaAuthorTwitter: "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn: "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub: "https://github.com/h-enk"
schemaLocale: en-US
schemaLogo: logo-hyas.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: hyas.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: "https://twitter.com/gethyas"
schemaLinkedIn: ""
schemaGitHub: "https://github.com/h-enk/hyas"
themeColor: "#3ac58d"
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: "320"
imageResponsive: true
imageConvertTo: webp
imageImageSizes:
  - "480"
  - "720"
  - "1080"
  - "1280"
  - "1600"
  - "2048"
singleSize: false
imageAddClass: img-fluid lazyload blur-up
defaultImage: default-image.png
fillImage: 1280x720 Center
alert: false
alertDismissable: true
alertText: >-
  Deliver web projects 10x faster. <a class="alert-link"
  href="https://www.netlify.com/whitepaper/" target="_blank" rel="noopener">Get
  the free enterprise paper →</a>
blogPageURL: blog
contactLink: contact
copyright: All right reserved copyright © Helmani 2022
footerLogo: images/site-navigation/logo.png
footerContact:
  topTitle: Let's Start
  title: The Start of a Dream
  button: Get in Touch
fabformURL: "https://fabform.io/f/JpTXRUa"
googleAnalytics: YOUR GOOGLE ANALYTICS CODE
logo: images/site-navigation/logo.png
address:
  address: Torres Médicas II Angelopolis Consultorio 602, Puebla
  email: contacto@cristalsarabia.com
  openingHours: "Lun a Vie: 9:00 A.M. - 6:00 P.M. Sábados: 9:00 A.M. - 2:00 P.M."
  phone: (+52) 222 359 0967
map:
  APIkey: YOUR GOOGLE MAP API
  latitude: "19.0201875"
  longitude: "-98.2676374"
  pinImage: images/pin.png
social:
  - icon: fa-facebook-official
    url: "https://www.facebook.com/"
    weight: 1
  - icon: fa-linkedin-square
    url: "https://www.linkedin.com/"
    weight: 2
  - icon: fa-pinterest-square
    url: "https://www.pinterest.com/"
    weight: 3
  - icon: fa-twitter-square
    url: "https://twitter.com/"
    weight: 4
